INSERT INTO users (id, name) VALUES (1, 'Dipkamal');
INSERT INTO users (id, name) VALUES (2, 'Tanvir');
INSERT INTO users (id, name) VALUES (3, 'Calua');

INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (1, 'cool t-shirt', 59.99, 18, 'Gildan is one of the world''s largest vertically integrated manufacturers of apparel and socks...', 't-shirt', 'https://ih1.redbubble.net/image.491441117.4117/gptr,1400x,front,black-c,188,133,1000,1000-bg,f8f8f8.u7.jpg');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (2, 'comfy t-shirt', 99.99, 8, 'Fruit of the Loom mens crews work great alone...', 't-shirt', 'https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (3, 'winter hoodie', 200.0, 10, 'Featuring our warmest fleece, the Hanes Ultimate® heavyweight hoodie...', 'hoodie', 'https://images.unsplash.com/photo-1613922110510-502f37d20eb9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (4, 'just hoodie', 100.0, 5, 'Equal parts durable, comfortable and stylish...', 'hoodie', 'https://images.unsplash.com/photo-1615397587950-3cbb55f95b77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (5, 'Cool Sweater', 100.0, 20, 'When soft comfort is what you seek...', 'sweater', 'https://m.media-amazon.com/images/I/91KOEKmjufL._AC_UY1000_.jpg');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (6, 'Cute Bodysuit', 40.0, 90, 'Our baby clothes are designed to keep your little one feeling at their best...', 'bodysuit', 'https://cdn.shopify.com/s/files/1/1407/3324/products/LS-Smiling-Baby_320x.progressive.jpg');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (7, 'Simple Joys Snap-Up Rompers', 50.0, 40, 'Our baby girl winter clothes are easy to wear and take off...', 'infant_t_romper', 'https://m.media-amazon.com/images/I/912Kcj04weL._AC_UY879_.jpg');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (8, 'Champion Men''s Classic Muscle Tee', 19.95, 20, 'Show off those muscles you''ve been building...', 'jersey_tank', 'https://m.media-amazon.com/images/I/61TartYQ1AL._AC_UX679_.jpg');
INSERT INTO product (id, name, price, quantity, description, type, image) VALUES (9, 'Hanes Sport Men''s Long-Sleeve T-Shirt', 39.95, 20, 'There''s nothing like the comfort and style of Hanes Men''s Clothing...', 'long_sleeve', 'https://m.media-amazon.com/images/I/61WjFrh4lLL._AC_UX679_.jpg');
