CREATE TABLE product (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price FLOAT,
    quantity INT,
    description TEXT,
    type VARCHAR(50),
    image VARCHAR(255)
);

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE estore_orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    order_date VARCHAR(50),
    address VARCHAR(255)
    -- FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE shopping_cart_item (
    shopping_cart_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT,
    color VARCHAR(50),
    size VARCHAR(50),
    image VARCHAR(255),
    user_id INT,
    shopping_cart_quantity INT,
    order_id INT,
    -- FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (order_id) REFERENCES estore_orders(order_id)
);
