version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: estore_db
      MYSQL_ROOT_PASSWORD: Srinu582004
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./estore-api
    restart: always
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3306/estore_db?useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: Srinu582004
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./estore-ui
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
